name: publish-wheels-aarch64

on: [push, workflow_dispatch]

jobs:

  build-aarch64-wheels:
    runs-on: ubuntu-latest
    env:
      MATURIN_USERNAME: ${{ secrets.PYPI_USERNAME_FXP }}
      MATURIN_PASSWORD: ${{ secrets.PYPI_PASSWORD_FXP }}
      img: quay.io/pypa/manylinux2014_aarch64
    steps:
     - name: Checkout
       uses: actions/checkout@v1
     - name: "Set up QEMU"
       id: qemu
       uses: docker/setup-qemu-action@v1
     - name: Install dependencies
       run: |
         docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
         -e MATURIN_USERNAME=${{ env.MATURIN_USERNAME }} \
         -e MATURIN_PASSWORD=${{ env.MATURIN_PASSWORD}} \
         ${{ env.img }} \
         bash -exc 'curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
           source $HOME/.cargo/env && \
           echo "$PWD" && ls -lrth && \
           cd crates/cli && echo "$PWD" && \
           for PYBIN in /opt/python/cp38*/bin; do
             "${PYBIN}/pip" install maturin
             "${PYBIN}/maturin" publish -b bin -i "${PYBIN}/python" --no-sdist --skip-existing --compatibility manylinux2014 --username "$MATURIN_USERNAME" --config "net.git-fetch-with-cli = true"
             "${PYBIN}/maturin" publish -b bin -i "${PYBIN}/python" --no-sdist --skip-existing --compatibility musllinux_1_2 --username "$MATURIN_USERNAME" --config "net.git-fetch-with-cli = true"
           done'


