name: TestWASM

on: [push, workflow_dispatch]

jobs:
  wasmtest:
    name: Test WASM
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh 
    - name: WASM test
      run: |
        echo "no tests so far, but check that it compiles!"
        source $HOME/.cargo/env      
        cd crates/wasm
        wasm-pack test --node

